"""resume quality rating

Revision ID: 740fe68c97f8
Revises: 8904d968f5cd
Create Date: 2026-08-08 08:33:40.033246

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "740fe68c97f8"
down_revision: str | None = "8904d968f5cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resume_profiles",
        sa.Column(
            "quality",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
            # Same reason as the `generated` flag: a NOT NULL column added to a
            # table with rows needs a default for those rows to satisfy it.
            # Dropped afterwards so the application default owns new rows.
            server_default=sa.text("'{}'"),
        ),
    )
    op.alter_column("resume_profiles", "quality", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resume_profiles", "quality")
    # ### end Alembic commands ###
