"""initial schema

Revision ID: 820aeb455446
Revises:
Create Date: 2026-07-28 03:20:29.268482

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "820aeb455446"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competency_taxonomy",
        sa.Column("competency_id", sa.String(length=80), nullable=False),
        sa.Column("domain", sa.String(length=48), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("competency_id", name=op.f("pk_competency_taxonomy")),
    )
    op.create_index(
        op.f("ix_competency_taxonomy_created_at"),
        "competency_taxonomy",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_competency_taxonomy_domain"), "competency_taxonomy", ["domain"], unique=False
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("is_personal", sa.Boolean(), nullable=False),
        sa.Column("media_retention_days", sa.Integer(), nullable=False),
        sa.Column("transcript_retention_days", sa.Integer(), nullable=False),
        sa.Column("candidate_feedback_visibility", sa.String(length=24), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_index(
        op.f("ix_organizations_created_at"), "organizations", ["created_at"], unique=False
    )
    op.create_table(
        "outbox_events",
        sa.Column("aggregate_type", sa.String(length=48), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        op.f("ix_outbox_events_aggregate_id"), "outbox_events", ["aggregate_id"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_created_at"), "outbox_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_event_type"), "outbox_events", ["event_type"], unique=False
    )
    op.create_index(
        "ix_outbox_events_unpublished", "outbox_events", ["status", "created_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("training_opt_in", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=48), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_log_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_log_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)
    op.create_index(
        "ix_audit_log_resource",
        "audit_log",
        ["resource_type", "resource_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "job_descriptions",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_job_descriptions_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_job_descriptions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_descriptions")),
    )
    op.create_index(
        op.f("ix_job_descriptions_created_at"), "job_descriptions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_job_descriptions_created_by_user_id"),
        "job_descriptions",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_descriptions_organization_id"),
        "job_descriptions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "org_members",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_org_members_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_org_members_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_members")),
        sa.UniqueConstraint("organization_id", "user_id", name="uq_org_members_organization_id"),
    )
    op.create_index(op.f("ix_org_members_created_at"), "org_members", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_org_members_organization_id"), "org_members", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_org_members_user_id"), "org_members", ["user_id"], unique=False)
    op.create_table(
        "question_bank",
        sa.Column("competency_id", sa.String(length=80), nullable=False),
        sa.Column("seniority", sa.String(length=16), nullable=False),
        sa.Column("rubric_version", sa.Integer(), nullable=False),
        sa.Column("rubric_family", sa.String(length=16), nullable=False),
        sa.Column("archetype", sa.String(length=24), nullable=False),
        sa.Column("neutral_wording", sa.Text(), nullable=False),
        sa.Column("reframe_wording", sa.Text(), nullable=True),
        sa.Column("expected_minutes", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competency_taxonomy.competency_id"],
            name=op.f("fk_question_bank_competency_id_competency_taxonomy"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_bank")),
        sa.UniqueConstraint(
            "competency_id",
            "seniority",
            "rubric_version",
            name="uq_question_bank_competency_seniority_version",
        ),
    )
    op.create_index(
        op.f("ix_question_bank_created_at"), "question_bank", ["created_at"], unique=False
    )
    op.create_index(
        "ix_question_bank_lookup",
        "question_bank",
        ["competency_id", "seniority", "active"],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_created_at"), "refresh_tokens", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "resumes",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_resumes_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_resumes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resumes")),
    )
    op.create_index(op.f("ix_resumes_created_at"), "resumes", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_resumes_organization_id"), "resumes", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_resumes_user_id"), "resumes", ["user_id"], unique=False)
    op.create_table(
        "bank_rubric_concepts",
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("concept_id", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("weight", sa.String(length=16), nullable=False),
        sa.Column("why_it_matters", sa.Text(), nullable=False),
        sa.Column("signpost", sa.Text(), nullable=True),
        sa.Column(
            "acceptable_signals",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "common_misconceptions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question_bank.id"],
            name=op.f("fk_bank_rubric_concepts_question_id_question_bank"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_rubric_concepts")),
        sa.UniqueConstraint("question_id", "concept_id", name="uq_bank_rubric_concepts_concept_id"),
    )
    op.create_index(
        op.f("ix_bank_rubric_concepts_created_at"),
        "bank_rubric_concepts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bank_rubric_concepts_question_id"),
        "bank_rubric_concepts",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "golden_answers",
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=32), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column(
            "expected_verdicts",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question_bank.id"],
            name=op.f("fk_golden_answers_question_id_question_bank"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_golden_answers")),
    )
    op.create_index(
        op.f("ix_golden_answers_created_at"), "golden_answers", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_golden_answers_question_id"), "golden_answers", ["question_id"], unique=False
    )
    op.create_table(
        "jd_versions",
        sa.Column("job_description_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "injection_flags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("thin", sa.Boolean(), nullable=False),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_description_id"],
            ["job_descriptions.id"],
            name=op.f("fk_jd_versions_job_description_id_job_descriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jd_versions")),
        sa.UniqueConstraint(
            "job_description_id", "version", name="uq_jd_versions_job_description_id"
        ),
    )
    op.create_index(op.f("ix_jd_versions_created_at"), "jd_versions", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_jd_versions_job_description_id"),
        "jd_versions",
        ["job_description_id"],
        unique=False,
    )
    op.create_table(
        "resume_versions",
        sa.Column("resume_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "injection_flags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
            name=op.f("fk_resume_versions_resume_id_resumes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resume_versions")),
        sa.UniqueConstraint("resume_id", "version", name="uq_resume_versions_resume_id"),
    )
    op.create_index(
        op.f("ix_resume_versions_created_at"), "resume_versions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_resume_versions_resume_id"), "resume_versions", ["resume_id"], unique=False
    )
    op.create_table(
        "jd_profiles",
        sa.Column("jd_version_id", sa.UUID(), nullable=False),
        sa.Column("role_title", sa.String(length=200), nullable=True),
        sa.Column("seniority", sa.String(length=16), nullable=True),
        sa.Column("domain", sa.String(length=48), nullable=True),
        sa.Column(
            "responsibilities",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["jd_version_id"],
            ["jd_versions.id"],
            name=op.f("fk_jd_profiles_jd_version_id_jd_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jd_profiles")),
    )
    op.create_index(op.f("ix_jd_profiles_created_at"), "jd_profiles", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_jd_profiles_jd_version_id"), "jd_profiles", ["jd_version_id"], unique=True
    )
    op.create_table(
        "postings",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("jd_version_id", sa.UUID(), nullable=True),
        sa.Column(
            "template",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["jd_version_id"],
            ["jd_versions.id"],
            name=op.f("fk_postings_jd_version_id_jd_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_postings_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_postings")),
    )
    op.create_index(op.f("ix_postings_created_at"), "postings", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_postings_organization_id"), "postings", ["organization_id"], unique=False
    )
    op.create_table(
        "resume_profiles",
        sa.Column("resume_version_id", sa.UUID(), nullable=False),
        sa.Column(
            "identity",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("raw_text_chars", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resume_version_id"],
            ["resume_versions.id"],
            name=op.f("fk_resume_profiles_resume_version_id_resume_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resume_profiles")),
    )
    op.create_index(
        op.f("ix_resume_profiles_created_at"), "resume_profiles", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_resume_profiles_resume_version_id"),
        "resume_profiles",
        ["resume_version_id"],
        unique=True,
    )
    op.create_table(
        "interview_sessions",
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("posting_id", sa.UUID(), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("target_minutes", sa.Integer(), nullable=False),
        sa.Column("seniority", sa.String(length=16), nullable=False),
        sa.Column("domain", sa.String(length=48), nullable=True),
        sa.Column("resume_version_id", sa.UUID(), nullable=True),
        sa.Column("jd_version_id", sa.UUID(), nullable=True),
        sa.Column("current_question_ordinal", sa.Integer(), nullable=False),
        sa.Column("accommodation", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("graded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["jd_version_id"],
            ["jd_versions.id"],
            name=op.f("fk_interview_sessions_jd_version_id_jd_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_interview_sessions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["posting_id"],
            ["postings.id"],
            name=op.f("fk_interview_sessions_posting_id_postings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resume_version_id"],
            ["resume_versions.id"],
            name=op.f("fk_interview_sessions_resume_version_id_resume_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_interview_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_sessions")),
    )
    op.create_index(
        op.f("ix_interview_sessions_created_at"), "interview_sessions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_interview_sessions_organization_id"),
        "interview_sessions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_interview_sessions_posting_status",
        "interview_sessions",
        ["posting_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_sessions_status"), "interview_sessions", ["status"], unique=False
    )
    op.create_index(
        "ix_interview_sessions_user_created",
        "interview_sessions",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_sessions_user_id"), "interview_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "jd_requirements",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("competency_id", sa.String(length=80), nullable=False),
        sa.Column("weight", sa.String(length=16), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competency_taxonomy.competency_id"],
            name=op.f("fk_jd_requirements_competency_id_competency_taxonomy"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["jd_profiles.id"],
            name=op.f("fk_jd_requirements_profile_id_jd_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jd_requirements")),
    )
    op.create_index(
        op.f("ix_jd_requirements_created_at"), "jd_requirements", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_jd_requirements_profile_id"), "jd_requirements", ["profile_id"], unique=False
    )
    op.create_table(
        "profile_items",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("source_span_start", sa.Integer(), nullable=False),
        sa.Column("source_span_end", sa.Integer(), nullable=False),
        sa.Column("prominence", sa.Integer(), nullable=False),
        sa.Column(
            "corrected_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("corrected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["resume_profiles.id"],
            name=op.f("fk_profile_items_profile_id_resume_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_items")),
    )
    op.create_index(
        op.f("ix_profile_items_created_at"), "profile_items", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_profile_items_kind"), "profile_items", ["kind"], unique=False)
    op.create_index(
        op.f("ix_profile_items_profile_id"), "profile_items", ["profile_id"], unique=False
    )
    op.create_table(
        "consents",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("consent_version", sa.String(length=24), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "disclosures",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["interview_sessions.id"],
            name=op.f("fk_consents_session_id_interview_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_consents_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consents")),
    )
    op.create_index(op.f("ix_consents_created_at"), "consents", ["created_at"], unique=False)
    op.create_index(op.f("ix_consents_session_id"), "consents", ["session_id"], unique=False)
    op.create_index(op.f("ix_consents_user_id"), "consents", ["user_id"], unique=False)
    op.create_table(
        "fit_map_entries",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("competency_id", sa.String(length=80), nullable=False),
        sa.Column("fit", sa.String(length=16), nullable=False),
        sa.Column("jd_weight", sa.String(length=16), nullable=False),
        sa.Column(
            "evidence_item_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competency_taxonomy.competency_id"],
            name=op.f("fk_fit_map_entries_competency_id_competency_taxonomy"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["interview_sessions.id"],
            name=op.f("fk_fit_map_entries_session_id_interview_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fit_map_entries")),
        sa.UniqueConstraint("session_id", "competency_id", name="uq_fit_map_entries_session_id"),
    )
    op.create_index(
        op.f("ix_fit_map_entries_created_at"), "fit_map_entries", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_fit_map_entries_session_id"), "fit_map_entries", ["session_id"], unique=False
    )
    op.create_table(
        "reduction_results",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "competency_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("seniority", sa.String(length=16), nullable=False),
        sa.Column("domain", sa.String(length=48), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column(
            "discarded_candidates",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["interview_sessions.id"],
            name=op.f("fk_reduction_results_session_id_interview_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reduction_results")),
    )
    op.create_index(
        op.f("ix_reduction_results_created_at"), "reduction_results", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_reduction_results_session_id"), "reduction_results", ["session_id"], unique=True
    )
    op.create_table(
        "session_questions",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("competency_id", sa.String(length=80), nullable=False),
        sa.Column("seniority", sa.String(length=16), nullable=False),
        sa.Column("bank_question_id", sa.UUID(), nullable=False),
        sa.Column("rubric_version", sa.Integer(), nullable=False),
        sa.Column("rubric_family", sa.String(length=16), nullable=False),
        sa.Column("neutral_wording", sa.Text(), nullable=False),
        sa.Column("reframe_wording", sa.Text(), nullable=True),
        sa.Column("framing_text", sa.Text(), nullable=True),
        sa.Column("source_profile_item_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("asked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hint_count", sa.Integer(), nullable=False),
        sa.Column("followup_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bank_question_id"],
            ["question_bank.id"],
            name=op.f("fk_session_questions_bank_question_id_question_bank"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competency_taxonomy.competency_id"],
            name=op.f("fk_session_questions_competency_id_competency_taxonomy"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["interview_sessions.id"],
            name=op.f("fk_session_questions_session_id_interview_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_profile_item_id"],
            ["profile_items.id"],
            name=op.f("fk_session_questions_source_profile_item_id_profile_items"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_questions")),
        sa.UniqueConstraint("session_id", "ordinal", name="uq_session_questions_session_id"),
    )
    op.create_index(
        op.f("ix_session_questions_created_at"), "session_questions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_session_questions_session_id"), "session_questions", ["session_id"], unique=False
    )
    op.create_table(
        "usage_costs",
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("units", sa.Float(), nullable=False),
        sa.Column("usd", sa.Float(), nullable=False),
        sa.Column("vendor", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["interview_sessions.id"],
            name=op.f("fk_usage_costs_session_id_interview_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_usage_costs_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_costs")),
    )
    op.create_index(op.f("ix_usage_costs_created_at"), "usage_costs", ["created_at"], unique=False)
    op.create_index("ix_usage_costs_session", "usage_costs", ["session_id"], unique=False)
    op.create_index(
        "ix_usage_costs_user_created", "usage_costs", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "answers",
        sa.Column("session_question_id", sa.UUID(), nullable=False),
        sa.Column("turn_index", sa.Integer(), nullable=False),
        sa.Column("prompt_text", sa.Text(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("input_mode", sa.String(length=16), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("skipped", sa.Boolean(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_question_id"],
            ["session_questions.id"],
            name=op.f("fk_answers_session_question_id_session_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answers")),
        sa.UniqueConstraint("idempotency_key", name="uq_answers_idempotency_key"),
        sa.UniqueConstraint(
            "session_question_id", "turn_index", name="uq_answers_session_question_id"
        ),
    )
    op.create_index(op.f("ix_answers_created_at"), "answers", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_answers_session_question_id"), "answers", ["session_question_id"], unique=False
    )
    op.create_table(
        "hints",
        sa.Column("session_question_id", sa.UUID(), nullable=False),
        sa.Column("level", sa.String(length=24), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "touched_concept_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_question_id"],
            ["session_questions.id"],
            name=op.f("fk_hints_session_question_id_session_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hints")),
    )
    op.create_index(op.f("ix_hints_created_at"), "hints", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_hints_session_question_id"), "hints", ["session_question_id"], unique=False
    )
    op.create_table(
        "rubric_concepts",
        sa.Column("session_question_id", sa.UUID(), nullable=False),
        sa.Column("concept_id", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("weight", sa.String(length=16), nullable=False),
        sa.Column("why_it_matters", sa.Text(), nullable=False),
        sa.Column("signpost", sa.Text(), nullable=True),
        sa.Column(
            "acceptable_signals",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "common_misconceptions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("hint_touched", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_question_id"],
            ["session_questions.id"],
            name=op.f("fk_rubric_concepts_session_question_id_session_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rubric_concepts")),
        sa.UniqueConstraint(
            "session_question_id", "concept_id", name="uq_rubric_concepts_session_question_id"
        ),
    )
    op.create_index(
        op.f("ix_rubric_concepts_created_at"), "rubric_concepts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_rubric_concepts_session_question_id"),
        "rubric_concepts",
        ["session_question_id"],
        unique=False,
    )
    op.create_table(
        "evaluations",
        sa.Column("answer_id", sa.UUID(), nullable=False),
        sa.Column("session_question_id", sa.UUID(), nullable=False),
        sa.Column("rubric_version", sa.Integer(), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("quarantine_reason", sa.Text(), nullable=True),
        sa.Column(
            "raw_output",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("raw_score", sa.Float(), nullable=True),
        sa.Column("hint_adjusted_score", sa.Float(), nullable=True),
        sa.Column("band", sa.Integer(), nullable=True),
        sa.Column(
            "terminology_notes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("graded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answers.id"],
            name=op.f("fk_evaluations_answer_id_answers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_question_id"],
            ["session_questions.id"],
            name=op.f("fk_evaluations_session_question_id_session_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluations")),
        sa.UniqueConstraint(
            "answer_id",
            "rubric_version",
            "model_version",
            "prompt_version",
            name="uq_evaluations_answer_id",
        ),
    )
    op.create_index(op.f("ix_evaluations_answer_id"), "evaluations", ["answer_id"], unique=False)
    op.create_index(op.f("ix_evaluations_created_at"), "evaluations", ["created_at"], unique=False)
    op.create_index(
        "ix_evaluations_question",
        "evaluations",
        ["session_question_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "transcript_segments",
        sa.Column("answer_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("low_confidence", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answers.id"],
            name=op.f("fk_transcript_segments_answer_id_answers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_segments")),
    )
    op.create_index(
        op.f("ix_transcript_segments_answer_id"), "transcript_segments", ["answer_id"], unique=False
    )
    op.create_index(
        op.f("ix_transcript_segments_created_at"),
        "transcript_segments",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "concept_assessments",
        sa.Column("evaluation_id", sa.UUID(), nullable=False),
        sa.Column("concept_id", sa.String(length=64), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("evidence_quote", sa.Text(), nullable=True),
        sa.Column("has_evidence", sa.Boolean(), nullable=False),
        sa.Column("hint_discounted", sa.Boolean(), nullable=False),
        sa.Column("improvement_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_concept_assessments_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concept_assessments")),
        sa.UniqueConstraint(
            "evaluation_id", "concept_id", name="uq_concept_assessments_evaluation_id"
        ),
    )
    op.create_index(
        op.f("ix_concept_assessments_created_at"),
        "concept_assessments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_concept_assessments_evaluation_id"),
        "concept_assessments",
        ["evaluation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_concept_assessments_verdict"), "concept_assessments", ["verdict"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_concept_assessments_verdict"), table_name="concept_assessments")
    op.drop_index(op.f("ix_concept_assessments_evaluation_id"), table_name="concept_assessments")
    op.drop_index(op.f("ix_concept_assessments_created_at"), table_name="concept_assessments")
    op.drop_table("concept_assessments")
    op.drop_index(op.f("ix_transcript_segments_created_at"), table_name="transcript_segments")
    op.drop_index(op.f("ix_transcript_segments_answer_id"), table_name="transcript_segments")
    op.drop_table("transcript_segments")
    op.drop_index("ix_evaluations_question", table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_created_at"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_answer_id"), table_name="evaluations")
    op.drop_table("evaluations")
    op.drop_index(op.f("ix_rubric_concepts_session_question_id"), table_name="rubric_concepts")
    op.drop_index(op.f("ix_rubric_concepts_created_at"), table_name="rubric_concepts")
    op.drop_table("rubric_concepts")
    op.drop_index(op.f("ix_hints_session_question_id"), table_name="hints")
    op.drop_index(op.f("ix_hints_created_at"), table_name="hints")
    op.drop_table("hints")
    op.drop_index(op.f("ix_answers_session_question_id"), table_name="answers")
    op.drop_index(op.f("ix_answers_created_at"), table_name="answers")
    op.drop_table("answers")
    op.drop_index("ix_usage_costs_user_created", table_name="usage_costs")
    op.drop_index("ix_usage_costs_session", table_name="usage_costs")
    op.drop_index(op.f("ix_usage_costs_created_at"), table_name="usage_costs")
    op.drop_table("usage_costs")
    op.drop_index(op.f("ix_session_questions_session_id"), table_name="session_questions")
    op.drop_index(op.f("ix_session_questions_created_at"), table_name="session_questions")
    op.drop_table("session_questions")
    op.drop_index(op.f("ix_reduction_results_session_id"), table_name="reduction_results")
    op.drop_index(op.f("ix_reduction_results_created_at"), table_name="reduction_results")
    op.drop_table("reduction_results")
    op.drop_index(op.f("ix_fit_map_entries_session_id"), table_name="fit_map_entries")
    op.drop_index(op.f("ix_fit_map_entries_created_at"), table_name="fit_map_entries")
    op.drop_table("fit_map_entries")
    op.drop_index(op.f("ix_consents_user_id"), table_name="consents")
    op.drop_index(op.f("ix_consents_session_id"), table_name="consents")
    op.drop_index(op.f("ix_consents_created_at"), table_name="consents")
    op.drop_table("consents")
    op.drop_index(op.f("ix_profile_items_profile_id"), table_name="profile_items")
    op.drop_index(op.f("ix_profile_items_kind"), table_name="profile_items")
    op.drop_index(op.f("ix_profile_items_created_at"), table_name="profile_items")
    op.drop_table("profile_items")
    op.drop_index(op.f("ix_jd_requirements_profile_id"), table_name="jd_requirements")
    op.drop_index(op.f("ix_jd_requirements_created_at"), table_name="jd_requirements")
    op.drop_table("jd_requirements")
    op.drop_index(op.f("ix_interview_sessions_user_id"), table_name="interview_sessions")
    op.drop_index("ix_interview_sessions_user_created", table_name="interview_sessions")
    op.drop_index(op.f("ix_interview_sessions_status"), table_name="interview_sessions")
    op.drop_index("ix_interview_sessions_posting_status", table_name="interview_sessions")
    op.drop_index(op.f("ix_interview_sessions_organization_id"), table_name="interview_sessions")
    op.drop_index(op.f("ix_interview_sessions_created_at"), table_name="interview_sessions")
    op.drop_table("interview_sessions")
    op.drop_index(op.f("ix_resume_profiles_resume_version_id"), table_name="resume_profiles")
    op.drop_index(op.f("ix_resume_profiles_created_at"), table_name="resume_profiles")
    op.drop_table("resume_profiles")
    op.drop_index(op.f("ix_postings_organization_id"), table_name="postings")
    op.drop_index(op.f("ix_postings_created_at"), table_name="postings")
    op.drop_table("postings")
    op.drop_index(op.f("ix_jd_profiles_jd_version_id"), table_name="jd_profiles")
    op.drop_index(op.f("ix_jd_profiles_created_at"), table_name="jd_profiles")
    op.drop_table("jd_profiles")
    op.drop_index(op.f("ix_resume_versions_resume_id"), table_name="resume_versions")
    op.drop_index(op.f("ix_resume_versions_created_at"), table_name="resume_versions")
    op.drop_table("resume_versions")
    op.drop_index(op.f("ix_jd_versions_job_description_id"), table_name="jd_versions")
    op.drop_index(op.f("ix_jd_versions_created_at"), table_name="jd_versions")
    op.drop_table("jd_versions")
    op.drop_index(op.f("ix_golden_answers_question_id"), table_name="golden_answers")
    op.drop_index(op.f("ix_golden_answers_created_at"), table_name="golden_answers")
    op.drop_table("golden_answers")
    op.drop_index(op.f("ix_bank_rubric_concepts_question_id"), table_name="bank_rubric_concepts")
    op.drop_index(op.f("ix_bank_rubric_concepts_created_at"), table_name="bank_rubric_concepts")
    op.drop_table("bank_rubric_concepts")
    op.drop_index(op.f("ix_resumes_user_id"), table_name="resumes")
    op.drop_index(op.f("ix_resumes_organization_id"), table_name="resumes")
    op.drop_index(op.f("ix_resumes_created_at"), table_name="resumes")
    op.drop_table("resumes")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_created_at"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_question_bank_lookup", table_name="question_bank")
    op.drop_index(op.f("ix_question_bank_created_at"), table_name="question_bank")
    op.drop_table("question_bank")
    op.drop_index(op.f("ix_org_members_user_id"), table_name="org_members")
    op.drop_index(op.f("ix_org_members_organization_id"), table_name="org_members")
    op.drop_index(op.f("ix_org_members_created_at"), table_name="org_members")
    op.drop_table("org_members")
    op.drop_index(op.f("ix_job_descriptions_organization_id"), table_name="job_descriptions")
    op.drop_index(op.f("ix_job_descriptions_created_by_user_id"), table_name="job_descriptions")
    op.drop_index(op.f("ix_job_descriptions_created_at"), table_name="job_descriptions")
    op.drop_table("job_descriptions")
    op.drop_index("ix_audit_log_resource", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_outbox_events_unpublished", table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_event_type"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_created_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_aggregate_id"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(op.f("ix_organizations_created_at"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_competency_taxonomy_domain"), table_name="competency_taxonomy")
    op.drop_index(op.f("ix_competency_taxonomy_created_at"), table_name="competency_taxonomy")
    op.drop_table("competency_taxonomy")
    # ### end Alembic commands ###
