"""mark

Revision ID: 8904d968f5cd
Revises: 0d422f44c598
Create Date: 2026-08-08 08:05:11.498875

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8904d968f5cd"
down_revision: str | None = "0d422f44c598"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # A server_default is required, not optional: the table already holds 64
    # authored rubrics, and adding a NOT NULL column without one fails on every
    # existing row. Dropped again afterwards so the application default stays
    # the single source of truth for new rows.
    op.add_column(
        "question_bank",
        sa.Column("generated", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("question_bank", "generated", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question_bank", "generated")
    # ### end Alembic commands ###
